import Container from "@/components/Container";
import Footer from "@/components/layout/footer/Footer";
import Header from "@/components/layout/header/Header";
// import Hero from "@/components/hero-section/Hero";
import Head from "next/head";
import Image from "next/image";
import { createContext, Dispatch, SetStateAction, useState } from "react";

export const context = createContext<
  | {
      whatProject: number;
      setProject: Dispatch<SetStateAction<number>>;
    }
  | any
>(0);

export default function Home() {
  const [whatProject, setProject] = useState(1);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <context.Provider
        value={{
          whatProject,
          setProject,
        }}
      >
        <main className=' max-w-9xl w-full min-h-screen bg-primary'>
          <Header />
          <Container />
          <Footer />
        </main>
      </context.Provider>
    </>
  );
}
