import Container from "@/components/Container";
import Hero from "@/components/hero-section/Hero";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' max-w-9xl w-full min-h-screen bg-primary'>
        <Container />
      </main>
    </>
  );
}
